"""updated release year column to be integer, again...

Revision ID: 108dcde1907c
Revises: defca6261ebf
Create Date: 2023-03-09 11:23:37.313914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108dcde1907c'
down_revision = 'defca6261ebf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
