"""created content table

Revision ID: d47055eb63a4
Revises: 8d660fce0f8d
Create Date: 2023-03-07 11:42:31.953613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47055eb63a4'
down_revision = '8d660fce0f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orig_title', sa.String(), nullable=True),
    sa.Column('orig_release', sa.DateTime(), nullable=True),
    sa.Column('adapt_title', sa.String(), nullable=True),
    sa.Column('adapt_release', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    # ### end Alembic commands ###
