"""updated release year column to be integer

Revision ID: defca6261ebf
Revises: 28bad9053a26
Create Date: 2023-03-09 11:11:44.955455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defca6261ebf'
down_revision = '28bad9053a26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
